/**
 * Collects every <IconPlaceholder /> in the registry and components/ui and writes one module per
 * icon library that re-exports only the icons in use, so the site can preview
 * blocks in any library. Fails if a usage is missing a library or names an icon
 * that the library does not export.
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join, relative, resolve } from 'path'

const LIBRARIES = {
  lucide: 'lucide-react',
  tabler: '@tabler/icons-react',
  hugeicons: '@hugeicons/core-free-icons',
  phosphor: '@phosphor-icons/react',
  remixicon: '@remixicon/react',
} as const

type Library = keyof typeof LIBRARIES

const root = process.cwd()
const registryDir = resolve(root, 'registry')
const iconsDir = resolve(registryDir, 'icons')
const outputDir = resolve(iconsDir, 'generated')

function listFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name)
    if (entry.isDirectory()) return path === iconsDir ? [] : listFiles(path)
    return /\.tsx?$/.test(entry.name) ? [path] : []
  })
}

const used = Object.fromEntries(
  Object.keys(LIBRARIES).map((library) => [library, new Set<string>()]),
) as Record<Library, Set<string>>
const errors: string[] = []

for (const file of [
  ...listFiles(registryDir),
  ...listFiles(resolve(root, 'components/ui')),
]) {
  const source = readFileSync(file, 'utf8')
  for (const match of source.matchAll(/<IconPlaceholder\b([\s\S]*?)\/>/g)) {
    const attributes = Object.fromEntries(
      [...match[1].matchAll(/(\w+)=['"]([^'"]+)['"]/g)].map(([, key, value]) => [
        key,
        value,
      ]),
    )
    for (const library of Object.keys(LIBRARIES) as Library[]) {
      const name = attributes[library]
      if (!name)
        errors.push(`${relative(root, file)}: missing "${library}" in ${match[0]}`)
      else used[library].add(name)
    }
  }
}

async function main() {
  for (const [library, packageName] of Object.entries(LIBRARIES) as [Library, string][]) {
    const exports = (await import(packageName)) as Record<string, unknown>
    for (const name of used[library]) {
      if (!(name in exports)) errors.push(`${packageName} has no export "${name}"`)
    }
  }

  if (errors.length) {
    // oxlint-disable-next-line no-console
    console.error(errors.join('\n'))
    process.exit(1)
  }

  for (const [library, packageName] of Object.entries(LIBRARIES) as [Library, string][]) {
    const names = [...used[library]].sort()
    const content = [
      '// Generated by scripts/generate-icons.ts. Do not edit.',
      `export {\n${names.map((name) => `  ${name},`).join('\n')}\n} from '${packageName}'`,
      '',
    ].join('\n')
    writeFileSync(join(outputDir, `${library}.ts`), content)
  }

  // oxlint-disable-next-line no-console
  console.log(`✓ Generated icon maps for ${used.lucide.size} icons`)
}

void main()
