/**
 * Downloads the shadcn/ui style sheets (Vega, Nova, Maia…) and keeps the rules
 * for the `cn-*` classes that components/ui uses. The site switches style by
 * swapping the `style-*` class on <html>, like https://ui.shadcn.com/create.
 *
 *   pnpm styles:sync
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs'
import { join, resolve } from 'path'

import { STYLES } from '@/lib/customizer'

const SOURCE =
  'https://raw.githubusercontent.com/shadcn-ui/ui/main/apps/v4/registry/styles'

const root = process.cwd()
const uiDir = resolve(root, 'components/ui')
const outputDir = resolve(root, 'app/styles')

/** Markers the shadcn CLI rewrites for options this site doesn't offer, like translucent menus. */
const CLI_MARKERS = new Set([
  'cn-font-heading',
  'cn-menu-target',
  'cn-menu-translucent',
  'cn-rtl-flip',
])

const used = new Set(
  readdirSync(uiDir).flatMap((file) =>
    [...readFileSync(join(uiDir, file), 'utf8').matchAll(/\bcn-[\w-]+/g)].map(
      ([name]) => name,
    ),
  ),
)

/** Top-level rules inside `.style-name { … }`, with their selectors. */
function topLevelRules(css: string) {
  const body = css.slice(css.indexOf('{') + 1, css.lastIndexOf('}'))
  const rules: { selector: string; text: string }[] = []
  let depth = 0
  let start = 0
  for (let index = 0; index < body.length; index++) {
    if (body.startsWith('/*', index)) {
      const end = body.indexOf('*/', index) + 2
      if (depth === 0) start = end
      index = end - 1
    } else if (body[index] === '{') {
      depth++
    } else if (body[index] === '}') {
      depth--
      if (depth === 0) {
        const text = body.slice(start, index + 1).trim()
        rules.push({ selector: text.slice(0, text.indexOf('{')), text })
        start = index + 1
      }
    }
  }
  return rules
}

function dedent(text: string) {
  const lines = text.split('\n')
  const indent = Math.min(
    ...lines
      .slice(1)
      .filter((line) => line.trim())
      .map((line) => line.search(/\S/)),
  )
  return lines
    .map((line, index) => (index === 0 ? line : line.slice(indent - 2)))
    .join('\n')
}

async function main() {
  for (const { value } of STYLES) {
    const name = `style-${value}`
    const response = await fetch(`${SOURCE}/${name}.css`)
    if (!response.ok) throw new Error(`${name}.css: ${response.status}`)
    const rules = topLevelRules(await response.text()).filter(({ selector }) =>
      [...selector.matchAll(/\.(cn-[\w-]+)/g)].some(
        ([, className]) => used.has(className) && !CLI_MARKERS.has(className),
      ),
    )
    const css = [
      '/* Generated by scripts/sync-styles.ts from shadcn/ui. Do not edit. */',
      `.${name} {`,
      rules.map(({ text }) => `  ${dedent(text)}`).join('\n\n'),
      '}',
      '',
    ].join('\n')
    writeFileSync(join(outputDir, `${name}.css`), css)
    // oxlint-disable-next-line no-console
    console.log(`✓ ${name}: ${rules.length} rules`)
  }
}

void main()
